<?php

namespace RestApiBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQueryBuilder($filter = '') 
    {
        $qb = $this->createQueryBuilder('item');
        if ($filter) {
            $qb->andWhere('item.amount = :filter')
            ->setParameter('filter', (int)$filter);
        }
        return $qb;
    }
}
